name       : haskell-optparse-applicative
version    : 0.15.1.0
release    : 3
source     :
    - https://hackage.haskell.org/package/optparse-applicative-0.15.1.0/optparse-applicative-0.15.1.0.tar.gz : 4db3675fd1e0594afdf079db46f4cd412d483835d703e7c07e1a1a37d6f046f3
license    : BSD-3-Clause
component  : programming.haskell
summary    : optparse-applicative is a haskell library for parsing options on the command line, providing a powerful applicative interface for composing these options.
description: |
    optparse-applicative is a haskell library for parsing options on the command line, providing a powerful applicative interface for composing these options.
builddeps  :
    - haskell-ansi-wl-pprint-devel
    - haskell-cabal-install
    - haskell-transformers-compat-devel
rundeps    :
    - devel:
        - haskell-ansi-wl-pprint-devel
        - haskell-transformers-compat-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
