name       : haskell-optparse-applicative
version    : 0.13.1.0
release    : 1
source     :
    - http://hackage.haskell.org/package/optparse-applicative-0.13.1.0/optparse-applicative-0.13.1.0.tar.gz : f1fcf9d7e78ddf14083a07d8fe1aa65d75c5102e0d44df981585bce54c5c2a2b
license    : BSD-3-Clause
component  : programming.haskell
summary    : optparse-applicative is a haskell library for parsing options on the command line, providing a powerful applicative interface for composing these options.
description: |
    optparse-applicative is a haskell library for parsing options on the command line, providing a powerful applicative interface for composing these options.
builddeps  :
    - haskell-ansi-wl-pprint
    - haskell-cabal-install
    - haskell-transformers-compat
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
